@startuml{othello.png}

class Othello {
}

abstract State {
}

class Board {
  +height: Integer
  +widht:  Integer
}

class Cell {
}

class Piece {
}

class Piece {
}

class Color {
  colors: String
}

class Pos {
  +{static} pos2id()
  +{static} id2pos()
  +{static} pos2int()
  +{static} calc_pos()
}

class Ready {
}

class Play {
  +next()
  +exec()
}

class Result {
}

abstract OutputInterface {
  +show_board()
  #{abstract} show_sell()
  -get_piece_type()
}

class Html {
  -image_size: Integer

  +show_board()
  #show_sell()
  -get_piece_type()
}

' Player {{{
abstract Player {
  +{abstract} piece
  +{abstract} put_piece()
}
class User {
  +piece
  +put_piece()
}
class User {
  +piece
  +put_piece()
}
' }}}

class Judge {
  +reverce()
  -reverce_piece()
}
class PlayerCreater {
  +{static} make_player()
}

' Rule {{{
class Rule {
  +piece_num: Integer
  +board_width: Integer
  +board_height: Integer

  +is_puttable?()
  +is_reverseble?()
  +is_same_piece?()
}

class NormalRule {
  +piece_num: Integer
  +board_width: Integer
  +board_height: Integer

  +is_puttable?()
  +is_reverseble?()
  +is_same_piece?()
}

class OriginalRule {
  +piece_num: Integer
  +board_width: Integer
  +board_height: Integer

  +is_puttable?()
  +is_reverseble?()
  +is_same_piece?()
}
class RuleCreater {
  +{static} make_rule
}
' }}}

' 関連 {{{
Othello "1" o-- "*" State
Othello "1" --> "1" OutputInterface
Othello "1" o-- "1" Board
Othello "1" --> "1" PlayerCreater
Othello "1" --> "1" RuleCreater

State <|-- Ready
State <|-- Play
State <|-- Result

Board "1" --> "1" Pos
Board "1" o-- "*" Cell

RuleCreater ..> Rule : {use}
Rule <|-- NormalRule
Rule <|-- OriginalRule

PlayerCreater ..> Player : {use}
Player <|-- User
Player <|-- Cpu

Cell  "1" o-- "1" Piece
Piece "1" o-- "1" Color

OutputInterface <|-- Html
' }}}

@enduml
