@startuml{othello.png}

class Othello {
}

abstract State {
}

class Board {
  +height: Integer
  +widht: Integer
}

class Cell {
}

class Piece {
}
class Color {
  colors: String
}

class Pos {
  +{static} pos2id()
  +{static} id2pos()
  +{static} pos2int()
  +{static} calc_pos()
}

class Ready {
}

class Play {
  +next()
  +exec()
}

class Result {
}

abstract OutputInterface {
  +show_board()
  #{abstract} show_sell()
  -get_piece_type()
}

class Html {
  -image_size: Integer

  +show_board()
  #show_sell()
  -get_piece_type()
}
class Player {
  +piece
  +put_piece()
}

Othello "1" o-- "*" State

State <|-- Ready
State <|-- Play
State <|-- Result
State "1" --> "1" OutputInterface
State "1" --> "1" Board
State "1" --> "2..4" Player
State "1" --> "1" Rule

Board "1" --> "1" Pos
Board "1" o-- "*" Cell

Cell "1" o-- "1" Piece
Piece "1" o-- "1" Color

OutputInterface <|-- Html

@enduml
